# -*- coding: utf-8 -*-
"""Module-1-Lab-weather-pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPR0HgSh8pdrx7X8WCRuCMFdhIgnor6D

Time-series forecasting and prediction on tabular data using PyTorch. Supports Jetson Nano, TX1/TX2, AGX Xavier, and Xavier NX.

# Weather Forecasting

In this hourly [weather dataset](https://www.kaggle.com/selfishgene/historical-hourly-weather-data), we are forecasting the future weather of a city based on it's past weather. The following data is provided on 1-hour intervals (over a timespan of 40,000 hours):

- temperature
- humidity
- pressure
- wind_direction
- wind_speed

# Getting Started

## Software Requirement

- PyTorch
- CUDA

## Starting the container
"""

!git clone https://github.com/dusty-nv/pytorch-timeseries

cd pytorch-timeseries

!docker/run.sh

cd pytorch-timeseries

"""# Running the training script

Train.py allows you to:

- pick any number of inputs / outputs
- support both regression and classification
- easily change the model
- automatic plotting

Let's start by forecasting just the temperature:
"""

!python3 train.py --data data/weather.csv --inputs temperature --outputs temperature --horizon 1

"""Next we can incorporate multiple inputs/outputs and simultaneously predict the temperature, humidity, and barometric pressure:"""

!python3 train.py --data data/weather.csv --inputs temperature,humidity,pressure --outputs temperature,humidity,pressure --horizon 1

"""# Notes

We provide the model files for GRU RNN model and linear model in this repo. Please check the model files in ../models/

# What's next?

* For the lab exercise, we encourage you to source
your own data, prepare it, and then make a model with train.py.   

* Datasets typically require a little preparation, you can see those
scripts here:

  https://github.com/dusty-nv/pytorch-timeseries/tree/main/scripts
"""

