# -*- coding: utf-8 -*-
"""Module-1-Lab-solar-power-pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdgHUqexdslU4req7WbPT8wtPQb6CEBb

Time-series forecasting and prediction on tabular data using PyTorch. Supports Jetson Nano, TX1/TX2, AGX Xavier, and Xavier NX.

# Solar Power Prediction

This [dataset](https://www.kaggle.com/anikannal/solar-power-generation-data) contains solar panel power generation data along with environmental conditions from a solar power plant. The goal is to predict generated power given sthe ambient temperature and amount of sunlight. In this example, we are predicting 2 outputs (AC and DC power)

# Getting Started

## Software Requirement

- PyTorch
- CUDA

## Starting the container
"""

!git clone https://github.com/dusty-nv/pytorch-timeseries

cd pytorch-timeseries

!docker/run.sh

cd pytorch-timeseries

"""# Running the training script

Train.py allows you to:

- pick any number of inputs / outputs
- support both regression and classification
- easily change the model
- automatic plotting


"""

!python3 train.py --data data/solar_power.csv --inputs AMBIENT_TEMPERATURE,IRRADIATION --outputs DC_POWER,AC_POWER

"""# Notes

We provide the model files for GRU RNN model and linear model in this repo. Please check the model files in ../models/

# What's next?

* For the lab exercise, we encourage you to source
your own data, prepare it, and then make a model with train.py.   

* Datasets typically require a little preparation, you can see those
scripts here:

  https://github.com/dusty-nv/pytorch-timeseries/tree/main/scripts
"""

